server:
  port: 8761

spring:
  application:
    name: ${project.artifactId}

project:
  artifactId: '@project.artifactId@'
  name: '@project.name@'
  version: '@project.version@'
  description: '@project.description@'
  groupId: '@project.groupId@'