spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:leagueManagementTest;MODE=MySQL;
    username: sa
    password: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          default_schema:
          dialect: org.hibernate.dialect.H2Dialect
          jdbc:
            lob:
              non_contextual_creation: true
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/